[[redirects]]
  from = "/google*.html"
  to = "/google:splat.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "@netlify/plugin-sitemap"

[build]
  command = "npm run build"
  publish = "dist"

[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

[context.production]
  [context.production.environment]
    NODE_ENV = "production" 